### PR TITLE
Rebase firefox_share_fullscreen with origin/master

### PR DESCRIPTION
**Pull request by tuxayo**
Conflicts:
        conference.js
        lang/main.json

### CODE REVIEW

**Comment by tuxayo** [comment]
Wait only one pull request should have been merged. I guess it doesn't change anything as there is not difference between the code.

**Comment by tuxayo** [comment]
Wait I made the pull request against master >< sorry. I'm making new ones.

**Comment by hrotkogabor** [comment]
It was also strange to me. I will wait for the next one. Thanx

**Comment by tuxayo** [comment]
Here is #3 that uses a merge. I can't recreate the one with rebase which is obvious now because I rewrote the story. The only one who could have done a rebase would be you on your own branch.

If you prefer the version with a rebase, you should delete your branch, replace it locally with [mine](https://github.com/tuxayo/jitsi-meet/tree/firefox_share_fullscreen_solve_conflits_with_rebase) and force push.

**Comment by tuxayo** [comment]
Don't forget to delete your master branch which polluted by my erroneous PRs. To avoid potential future issues in case you forget that.

**Pull request merged**
